- name: Enable non-free repository
  apt_repository:
    repo: deb http://ftp.se.debian.org/debian/ stretch main non-free
  become: yes

- name: install required packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - conserver-server
  become: yes

- name: Remove init.d startup file
  file: 
    path: /etc/init.d/conserver-server
    state: absent

- name: Install systemd service file
  copy:
    src: files/conserver-server.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0755
  become: yes

- name: create conserver.cf file
  template:
    src: templates/conserver.cf.j2
    dest: /etc/conserver/conserver.cf
    owner: root
    group: root
    mode: 0644
  notify: restart conserver
  become: yes

- name: create conserver.passwd file
  template:
    src: templates/conserver.passwd.j2
    dest: /etc/conserver/conserver.passwd
    owner: root
    group: root
    mode: 0644
  notify: restart conserver
  become: yes

- name: ensure conserver is started and enabled
  service:
    name: conserver-server
    state: started
    enabled: yes
  become: yes
