---
- name: Create logfile path
  file:
    path: /var/log/conserver
    state: directory
  become: yes

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

