- name: install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - conserver
  become: yes

- name: create conserver.cf file
  template:
    src: conserver.cf.j2
    dest: /etc/conserver.cf
    owner: root
    group: root
    mode: 0644
  notify: restart conserver
  become: yes

- name: create conserver.passwd file
  template:
    src: conserver.passwd.j2
    dest: /etc/conserver.passwd
    owner: root
    group: root
    mode: 0644
  notify: restart conserver
  become: yes

- name: ensure conserver is started and enabled
  systemd:
    name: conserver
    state: started
    enabled: yes
  become: yes
